version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # MCP Server for data operations
  mcp-server:
    build:
      context: .
      dockerfile: ./mcp_server/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./mcp_server/data:/app/data
      - charts_volume:/app/charts
    environment:
      - MCP_DEBUG=true
      - MCP_TRANSPORT=http
      - PYTHONUNBUFFERED=1

  # PostgreSQL database for Phoenix
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: phoenix
      POSTGRES_PASSWORD: phoenix
      POSTGRES_DB: phoenix
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Phoenix Arize tracing server with PostgreSQL backend
  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"  # Phoenix UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://phoenix:phoenix@postgres:5432/phoenix
      - PHOENIX_PORT=6006
      - PHOENIX_HOST=0.0.0.0
      - PHOENIX_WORKING_DIR=/mnt/data
    volumes:
      - phoenix_data:/mnt/data
    depends_on:
      - postgres
    networks:
      - app-network

  # Unified Multi-Agent Application with Gradio Interface
  unified-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - PHOENIX_ENDPOINT=http://phoenix:6006
      - PHOENIX_PROJECT_NAME=agentic-app-quickstart
      - MCP_SERVER_URL=http://mcp-server:8000/mcp
      - MCP_DEBUG=true
      - INTERFACE=gradio

    networks:
      - app-network
    volumes:
      - charts_volume:/app/charts
    env_file: .env

  # Trajectory evaluation service  
  trajectory-evaluator:
    build: ./trajectory_evaluator
    env_file:
      - .env
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000/mcp
    volumes:
      - ./trajectory_evaluator/outputs:/app/outputs
    depends_on:
      - phoenix
      - mcp-server
    networks:
      - app-network
    # Uncomment to run evaluation automatically
    # command: sh -c "sleep 15 && python main.py --lookback-days 1"

volumes:
  postgres_data:
  phoenix_data:
  charts_volume:
